name: mcDungeons
main: com.coffeejawa.mcDungeons.mcDungeons
version: 0.5
authors: [tumland]
description: Worldguard Difficult allows monster difficulty adjustment in Worldguard regions.

softdepend: [ WorldGuard ]

commands:
    mcd:
        description: Root command for all  WorldguardDifficulty Commands.
        aliases: mcd
        usage: /mcd <region|level|debug> [add|set|list|reset|remove]
        permission: mcd.help
        permission-message: You require permission mcd.help to do that.
        
permissions:
    mcd.*:
        description: Gives access to all WorldguardDifficulty commands/functions.
        default: op
        children:
            mcd.add: true
            mcd.debug: true
            mcd.help: true
            mcd.remove: true
            mcd.set: true
            mcd.list: true
            mcd.reset: true
            mcd.edit: true

    mcd.add:
        description: Allows user to add region mappings.
        default: false
        
    mcd.set:
        description: Allows user to overwrite settings.
        default: false
        
    mcd.list:
        description: Allows user to list levels, regions and settings.
        default: false
        
    mcd.remove:
        description: Allow user to remove mapping for a region ID.
        default: false
        
    mcd.reset:
           description: Allow user to reset region to default settings.
           default: false
    
    mcd.debug:
        description: Allows user to toggle debug on and off.
        default: false

    mcd.help:
        description: Allows user to view command help text.
        default: false
        
    mcd.edit:
        description: Allows use to edit dungeons.
        default: false